"use client";

import { useState } from "react";
import AlertsFeed from "./AlertsFeed";
import NetworkMap from "./NetworkMap";
import type { SensorNode, Alert, HazardType } from "@/lib/mockData";
import { AlertTriangle, Cpu, Droplets, Flame, MapPin, Mountain, Thermometer, Wind, Zap } from "lucide-react";

interface OverviewTabProps { nodes: SensorNode[]; alerts: Alert[]; selectedNode: SensorNode | null; onNodeClick: (node: SensorNode) => void; onAcknowledge: (id: string) => void; onNotify: (id: string) => void; onAcknowledgeAll?: () => void; }
type HazardCard = { hazard: Exclude<HazardType, "Normal">; title: string; icon: React.ReactNode; tone: string; detail: string; action: string };

const HAZARDS: HazardCard[] = [
  { hazard: "Flood", title: "Flood watch", icon: <Droplets size={17} />, tone: "bg-sky-100 border-sky-200 text-sky-700", detail: "River height, rainfall and soil saturation are fused at the edge to spot an approaching breach.", action: "Prepare evacuation routes and deploy flood barriers." },
  { hazard: "Fire", title: "Fire watch", icon: <Flame size={17} />, tone: "bg-rose-100 border-rose-200 text-rose-700", detail: "Gas concentration, heat and humidity are checked together to reduce false alarms from a single sensor.", action: "Notify forest teams and stage first-response resources." },
  { hazard: "Pollution", title: "Air quality", icon: <Wind size={17} />, tone: "bg-violet-100 border-violet-200 text-violet-700", detail: "Particulate and gas readings highlight neighbourhood-scale exposure risks before public-health thresholds are crossed.", action: "Issue a targeted health advisory for vulnerable residents." },
  { hazard: "Landslide", title: "Slope watch", icon: <Mountain size={17} />, tone: "bg-amber-100 border-amber-200 text-amber-700", detail: "Rainfall, soil moisture and motion sensing identify unstable hillside conditions.", action: "Inspect the slope and keep evacuation corridors ready." },
  { hazard: "Extreme Heat", title: "Heat watch", icon: <Thermometer size={17} />, tone: "bg-orange-100 border-orange-200 text-orange-700", detail: "Temperature, humidity and local context provide a more useful heat-risk signal than temperature alone.", action: "Open cooling points and share heat-safety guidance." },
];

export default function OverviewTab({ nodes, alerts, selectedNode, onNodeClick, onAcknowledge, onNotify, onAcknowledgeAll }: OverviewTabProps) {
  const [selectedHazard, setSelectedHazard] = useState<HazardCard>(HAZARDS[0]);
  const hazardNodes = nodes.filter((node) => node.inference.hazardType === selectedHazard.hazard);
  const criticalCount = alerts.filter((alert) => alert.riskLevel === "Critical" && !alert.acknowledged).length;
  const activeNodeCount = nodes.filter((node) => node.status !== "Offline").length;
  return <div className="space-y-4">
    <section><div className="flex items-end justify-between gap-3 mb-3"><div><p className="text-[10px] uppercase tracking-[0.18em] font-bold text-teal-700">Purbavas at a glance</p><h2 className="text-lg font-black text-white">Calm, clear situational awareness</h2></div><span className="hidden sm:inline text-[10px] font-semibold text-slate-500">Updated from local edge nodes</span></div><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><div className="flex items-center gap-3 rounded-2xl border border-rose-200 bg-rose-50/85 p-3 shadow-sm"><div className="rounded-xl bg-rose-200/80 p-2.5 text-rose-700"><AlertTriangle size={18} /></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-rose-700">Critical alerts</p><p className="text-xl font-black text-rose-950">{criticalCount}</p><p className="text-[10px] text-rose-800/75">Needs responder acknowledgement</p></div></div><div className="flex items-center gap-3 rounded-2xl border border-amber-200 bg-amber-50/85 p-3 shadow-sm"><div className="rounded-xl bg-amber-200/80 p-2.5 text-amber-700"><MapPin size={18} /></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-amber-700">High-risk zone</p><p className="text-sm font-black text-amber-950">Assam</p><p className="text-[10px] text-amber-800/75">Brahmaputra flood-prone belt</p></div></div><div className="flex items-center gap-3 rounded-2xl border border-emerald-200 bg-emerald-50/85 p-3 shadow-sm"><div className="rounded-xl bg-emerald-200/80 p-2.5 text-emerald-700"><Cpu size={18} /></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-emerald-700">Active nodes</p><p className="text-xl font-black text-emerald-950">{activeNodeCount}<span className="ml-1 text-xs font-semibold">/ {nodes.length}</span></p><p className="text-[10px] text-emerald-800/75">Edge mesh reporting normally</p></div></div></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white/75 p-4 shadow-sm"><div className="flex items-center gap-2 mb-3"><div className="rounded-lg bg-teal-100 p-2 text-teal-700"><Zap size={15} /></div><div><h3 className="text-sm font-black text-white">Explore disaster signals</h3><p className="text-[11px] text-slate-500">Select a signal to see its precise area, live severity and suggested action.</p></div></div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-2">{HAZARDS.map((item) => { const count = nodes.filter((node) => node.inference.hazardType === item.hazard).length; const active = selectedHazard.hazard === item.hazard; return <button key={item.hazard} onClick={() => setSelectedHazard(item)} className={`text-left rounded-xl border p-3 transition-all hover:-translate-y-0.5 focus:outline-none focus:ring-2 focus:ring-teal-400 ${item.tone} ${active ? "ring-2 ring-teal-500 shadow-md" : "opacity-80 hover:opacity-100"}`}><div className="flex items-center justify-between"><span>{item.icon}</span><span className="rounded-full bg-white/70 px-1.5 py-0.5 text-[10px] font-bold">{count}</span></div><p className="mt-2 text-xs font-black">{item.title}</p><p className="mt-1 text-[10px] opacity-75">Open live details</p></button>; })}</div><div className="mt-3 rounded-xl border border-teal-100 bg-teal-50/65 p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black text-teal-900">{selectedHazard.title} · {hazardNodes.length} active node{hazardNodes.length === 1 ? "" : "s"}</p><p className="mt-1 max-w-2xl text-[11px] leading-relaxed text-teal-900/75">{selectedHazard.detail}</p></div><p className="rounded-lg bg-white/80 px-3 py-2 text-[11px] font-semibold text-teal-800">{selectedHazard.action}</p></div><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{hazardNodes.length ? hazardNodes.map((node) => <div key={node.id} className="rounded-lg border border-white/90 bg-white/85 p-2.5"><div className="flex items-center justify-between gap-2"><p className="text-[11px] font-black text-teal-950">{node.name}</p><span className={`rounded-full px-2 py-0.5 text-[9px] font-bold ${node.inference.riskLevel === "Critical" ? "bg-rose-100 text-rose-700" : node.inference.riskLevel === "Alert" ? "bg-orange-100 text-orange-700" : "bg-amber-100 text-amber-700"}`}>{node.inference.riskLevel}</span></div><p className="mt-1 text-[10px] text-teal-900/65">{node.location.zone}</p><div className="mt-2 flex items-center justify-between text-[10px]"><span className="font-semibold text-teal-800">AI confidence</span><span className="font-black text-teal-900">{node.inference.confidence}%</span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-teal-100"><div className="h-full rounded-full bg-teal-500" style={{ width: `${node.inference.confidence}%` }} /></div></div>) : <p className="text-[11px] text-teal-800/70">No active locations for this hazard right now.</p>}</div></div></section>
    <section className="space-y-2"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[0.18em] font-bold text-sky-700">Live map</p><h2 className="text-base font-black text-white">India-wide hazard view</h2></div><span className="text-[10px] text-slate-500">Click an icon to focus its alert</span></div><div className="h-[460px]"><NetworkMap nodes={nodes} onNodeClick={onNodeClick} selectedNodeId={selectedNode?.id ?? null} /></div></section>
    <section className="space-y-2"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[0.18em] font-bold text-rose-700">Incident command</p><h2 className="text-base font-black text-white">Verified alerts ready for action</h2></div><span className="text-[10px] text-slate-500">Confidence-aware · responder focused</span></div><AlertsFeed alerts={alerts} onAcknowledge={onAcknowledge} onNotify={onNotify} onAcknowledgeAll={onAcknowledgeAll} /></section>
  </div>;
}
